### ISSUE TITLE
Creating a (basic) player model, similar looking to a Garry's Mod character model

### ISSUE THREAD

**Issue by Arktikus** [Arktikus/echoes-of-yesterday#3]
**The goal here is to create a simple and basic player model.**
Some basic animations, low poly. Similar to a Garry's Mod character model, would be nice.

**It needs to have the following animations:**

- idle
- walk/run
- sit

**Task List:**

- [ ] Creating the model
- [ ] Animating the model
- [ ] Importing the model
- [ ] Setting it up
